server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luwojtaszek/springcloud-config-repository.git
          clone-on-start: true
          search-paths: MASTER
security:
  user:
    name: root
    password: s3cr3t